spring:

  cloud:
    discovery:
      client:
        composite-indicator:
          enabled: false

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/auth?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: auth
    password: koscom
    initialization-mode: always

  boot:
    admin:
      auto-deregistration: false
      client:
        url: http://msa-bootadmin.cf.intl
        username: admin
        password: koscom!234
        instance:
          service-url: http://${vcap.application.application_uris[0]}
          metadata:
            tags:
              Organization: ${vcap.application.organization_name}
              Space: ${vcap.application.space_name}
              APP-INDEX: ${vcap.application.instance_index}

config:
  swagger:
    enabled: true
  oauth2:
    client-id: jmworks
    client-secret: jmworksOauthSecret
    jwt-signkey: jmworksJwtSecret

management:
  endpoint:
    shutdown:
      enabled: false
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"