spring:

  cloud:
    discovery:
      client:
        composite-indicator:
          enabled: false

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

  boot:
    admin:
      auto-deregistration: false
      client:
        url: http://msa-bootadmin.cf.intl
        username: admin
        password: koscom!234
        instance:
          service-url: http://${vcap.application.application_uris[0]}
          metadata:
            tags:
              Organization: ${vcap.application.organization_name}
              Space: ${vcap.application.space_name}
              APP-INDEX: ${vcap.application.instance_index}

config:
  oauth2:
    url: http://localhost:8080/oauth/token
    clientId: jmworks
    clientSecret: jmworksOauthSecret
    jwt-signkey: jmworksJwtSecret
  swagger:
    enabled: false

management:
  endpoint:
    shutdown:
      enabled: false
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"