spring:

  cloud:
    discovery:
      client:
        composite-indicator:
          enabled: false

  jpa:
    hibernate:
      ddl-auto: update

  # h2:
  #   console:
  #     enabled: true
  #     settings:
  #       web-allow-others: true

  # datasource:
  #   driver-class-name: org.h2.Driver
  #   url: jdbc:h2:mem:todo
  #   username: todo
  #   password: koscom

  boot:
    admin:
      auto-deregistration: false
      client:
        url: http://msa-bootadmin.cf.intl
        username: admin
        password: koscom!234
        instance:
          service-url: http://${vcap.application.application_uris[0]}
          metadata:
            tags:
              Organization: ${vcap.application.organization_name}
              Space: ${vcap.application.space_name}
              APP-INDEX: ${vcap.application.instance_index}

security:
  swagger:
    enabled: false
  oauth2:
    jwt:
      signkey: jmworksJwtSecret

management:
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"        