spring:

  cloud:
    discovery:
      client:
        composite-indicator:
          enabled: false

    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
      routes:
        - id: auth
          uri: http://msa2-auth.cf.intl
          predicates:
            - Path=/api/auth/**
        - id: user
          uri: http://msa2-auth.cf.intl
          predicates:
            - Path=/api/user/**
        - id: todo
          uri: http://msa2-todo.cf.intl
          predicates:
            - Path=/api/todos/**
        - id: book
          uri: http://msa2-book.cf.intl
          predicates:
            - Path=/api/books/**

  jpa:
    hibernate:
      ddl-auto: update

  boot:
    admin:
      auto-deregistration: false
      client:
        url: http://msa-bootadmin.cf.intl
        username: admin
        password: koscom!234
        instance:
          service-url: http://${vcap.application.application_uris[0]}
          metadata:
            tags:
              Organization: ${vcap.application.organization_name}
              Space: ${vcap.application.space_name}
              APP-INDEX: ${vcap.application.instance_index}

management:
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"        

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
    